on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      - name: Build iOS IPA
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          ln -s ../Runner.app Payload/
          zip -r app.ipa Payload

      # Uncomment the following section if you want to push the artifacts to releases
      # - name: Push to Releases
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: |
      #       build/app/outputs/apk/release/*.apk
      #       build/ios/iphoneos/app.ipa
      #     tag: v1.0.${{ github.run_number }}
      #     token: ${{ secrets.TOKEN }}


# on:
#   pull_request:
#     branches:
#       - main
#       - master
#   push:
#     branches:
#       - main
#       - master
#       - develop
# name: "Build & Release"
# jobs:
#   build:
#     name: Build & Release
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-java@v3
#         with:
#           distribution: 'zulu'
#           java-version: '12'
#       - uses: subosito/flutter-action@v2
#         with:
#           channel: 'stable'
#           architecture: x64

#       - run: flutter build apk --release --split-per-abi
#       - run: |
#           flutter build ios --no-codesign
#           cd build/ios/iphoneos
#           mkdir Payload
#           cd Payload
#           ln -s ../Runner.app
#           cd ..
#           zip -r app.ipa Payload
      # - name: Push to Releasess
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
      #     tag: v1.0.${{ github.run_number }}
      #     token: ${{ secrets.TOKEN }}






# push to master, main, develop
# pull request on main master
